name: "infra-terraform-aws-github-oidc-pipeline"

on:
    workflow_dispatch: 
    push:
        branches: 
            - "master"
            - "develop"
            
env:
  TF_VERSION: 1.8.0
  ROLE_ARN: ${{ vars.ROLE_ARN }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_PLAN_PATH: "tfplan.json"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    name: "terraform-jobs"
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash

    steps:
        - name: "Setup Terraform"
          uses: hashicorp/setup-terraform@v2
          with: 
            terraform_version: ${{ env.TF_VERSION }}

        - name: "Git checkout"
          uses: actions/checkout@v3

        - name: "Configure AWS credentials"
          uses: aws-actions/configure-aws-credentials@v3
          with: 
            role-to-assume: ${{ env.ROLE_ARN }}
            role-session-name: "github-oidc-pipeline"
            aws-region: ${{ env.AWS_REGION }}
        
        - name: "Terraform init"
          run: terraform init

        - name: "Terraform format"
          run: terraform fmt -check -diff -recursive 
        
        - name: "Terraform plan"
          run: terraform plan -out={{env.TF_PLAN}} -input=false

        - name: "Terraform apply"
          run: terraform apply -auto-approve -input=false {{env.TF_PLAN}}

        
        
  
